#!/usr/bin/env python3
"""Pure constructor: elevated resolution + AEP → manifest.yaml + validate DirectivePacket."""

import json, hashlib, uuid, sys
from datetime import datetime, timezone
from pathlib import Path

def canonical(obj):
    return json.dumps(obj, sort_keys=True, separators=(",", ":"))

def sha256_of(obj):
    return hashlib.sha256(canonical(obj).encode()).hexdigest()

def main():
    if len(sys.argv) < 3:
        print("Usage: construct_manifest.py <resolution.json> <artifact_dir>")
        sys.exit(1)

    resolution = json.loads(Path(sys.argv[1]).read_text())
    artifact_dir = Path(sys.argv[2])
    aep = json.loads((artifact_dir / "aep.json").read_text())

    if not aep.get("elevation"):
        print("FAIL: AEP elevation is false – refusing to construct manifest")
        sys.exit(1)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
    project_id = str(uuid.uuid4())[:8]

    manifest = {
        "gfsa": {"schema": "0.2", "kind": "project-manifest"},
        "project": {
            "id": project_id,
            "name": resolution.get("decision", {}).get("requirement", "untitled")[:60],
            "version": "0.1.0",
            "goal_version": "0.1.0",
            "status": "contracted"
        },
        "intent": {
            "problem": resolution.get("decision", {}).get("requirement", ""),
            "task": "Resolve vehicle and produce build contract",
            "outcome": resolution.get("selected", "unknown")
        },
        "delivery": {
            "mode": "dynamic",
            "selected": resolution.get("selected"),
            "packageable": True,
            "beta_ready": False,
            "release_ready": False,
            "tier": 0,                    # will be overwritten by UI tier when available
            "evidence_gaps": [],
            "artifacts": [str(artifact_dir)]
        },
        "provenance": {
            "chain": ["USER_DECLARED", "OBSERVED", "RESEARCHED", "INFERRED", "SELECTED", "VERIFIED"],
            "header": aep.get("provenance")
        }
    }

    # Write manifest
    out = Path("state/projects/current")
    out.mkdir(parents=True, exist_ok=True)
    (out / "manifest.yaml").write_text(
        "# Generated by construct_manifest.py – do not edit by hand\n" +
        json.dumps(manifest, indent=2).replace('"', "")  # minimal YAML-ish for now
    )

    # Emit validate DirectivePacket
    directive = {
        "id": str(uuid.uuid4()),
        "stage": "validate",
        "actor": "system",
        "payload": {"manifest_id": project_id},
        "bindings": ["commit"],
        "metrics": {"latency_ms": 0, "size_bytes": 0, "hash_time_ms": 0},
        "timestamp": now
    }
    directive["metrics"]["size_bytes"] = len(canonical(directive).encode())
    content_hash = sha256_of(directive)
    provenance = f"{content_hash}:system:validate:{now}"

    validate_dir = Path("artifacts") / datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    validate_dir.mkdir(parents=True, exist_ok=True)
    (validate_dir / "directive.json").write_text(json.dumps(directive, indent=2))
    (validate_dir / "PROVENANCE").write_text(provenance + "\n")

    print(f"Manifest written → state/projects/current/manifest.yaml")
    print(f"Validate packet → {validate_dir}")
    print(f"Provenance: {provenance}")

if __name__ == "__main__":
    main()
